export { AboutPanel } from './AboutPanel'
export { SkillsPanel } from './SkillsPanel'
export { ExperiencePanel } from './ExperiencePanel'
export { ProjectsPanel } from './ProjectsPanel'
export { ArchitecturePanel } from './ArchitecturePanel'
export { DevOpsPanel } from './DevOpsPanel'
export { ContactPanel } from './ContactPanel'
export { panelVariants, SECTION_NAMES } from './shared'
